name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - python=3.11
  - xeus-python
  - ipycanvas
  # - conda-forge::sleap-io=0.1.9
  - conda-forge::sleap-io
